version: '3.0'
services:
    nginx:
        image: nginx:1.15.12-alpine
        container_name: nginx-svr
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - php
        links:
            - php
        volumes:
                - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
                - ./logs/nginx:/var/log/nginx
                - ./code:/var/www
        #command: [nginx-debug, '-g', 'daemon off;']
    php:
        build: ./php
        container_name: php-svr
        restart: always
        volumes:
            - ./code:/var/www
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        links:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql-svr
        restart: always
        ports:
          - "3307:3306"
        volumes:
          #- ./mysql/:/var/lib/mysql/:rw
          - ./logs/mysql/:/var/log/mysql/:rw
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
