version: '2.1'
services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        links:
            - php
        volumes:
                - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
                - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
                - ./logs/nginx:/var/log/nginx
                - ./code:/var/www/html
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
    php:
        build: ./php
        restart: always
        volumes:
            - ./code:/var/www/html
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
        links:
            - mysql
    mysql:
        image: mysql:5.7
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - ./mysql/:/var/lib/mysql/:rw
          - ./logs/mysql/:/var/log/mysql/:rw
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
